// Code generated by "stringer -type=FType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[image-0]
	_ = x[video-1]
	_ = x[audio-2]
}

const _FType_name = "imagevideoaudio"

var _FType_index = [...]uint8{0, 5, 10, 15}

func (i FType) String() string {
	if i >= FType(len(_FType_index)-1) {
		return "FType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FType_name[_FType_index[i]:_FType_index[i+1]]
}
